# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 330, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 330, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(70, 140, 261, 121))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(460, 140, 261, 121))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(60, 370, 261, 121))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(470, 370, 261, 121))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.btn_E = QtWidgets.QPushButton(self.centralwidget)
        self.btn_E.setGeometry(QtCore.QRect(80, 510, 75, 23))
        self.btn_E.setObjectName("btn_E")
        self.btn_D = QtWidgets.QPushButton(self.centralwidget)
        self.btn_D.setGeometry(QtCore.QRect(250, 510, 75, 23))
        self.btn_D.setObjectName("btn_D")
        self.btn_S = QtWidgets.QPushButton(self.centralwidget)
        self.btn_S.setGeometry(QtCore.QRect(470, 510, 75, 23))
        self.btn_S.setObjectName("btn_S")
        self.btn_V = QtWidgets.QPushButton(self.centralwidget)
        self.btn_V.setGeometry(QtCore.QRect(660, 510, 75, 23))
        self.btn_V.setObjectName("btn_V")
        self.btn_Ge = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Ge.setGeometry(QtCore.QRect(480, 40, 91, 23))
        self.btn_Ge.setObjectName("btn_Ge")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA Cipher"))
        self.label_2.setText(_translate("MainWindow", "Plaintext"))
        self.label_3.setText(_translate("MainWindow", "Ciphertext"))
        self.label_4.setText(_translate("MainWindow", "Signature"))
        self.label_5.setText(_translate("MainWindow", "Information"))
        self.btn_E.setText(_translate("MainWindow", "Encrypt"))
        self.btn_D.setText(_translate("MainWindow", "Decrypt"))
        self.btn_S.setText(_translate("MainWindow", "Sign"))
        self.btn_V.setText(_translate("MainWindow", "Verify"))
        self.btn_Ge.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
